### ISSUE TITLE
how to fineture with codeLlama-7B

### ISSUE THREAD

**Issue by deepforest7** [smallcloudai/refact#453]
hi, I just found few model in webui. I have success finture with startcode2. And I saw there also support codellama-7b, my question is how to fineture with codellama-7b? do we need modified code

**Comment by deepforest7** [comment]
note codellama is not support to finetune. if I must to finetune it, I can just add "finetune" to huggingface.py - codellama like? 
![image](https://github.com/user-attachments/assets/d7a925e4-7869-48e4-8184-946f581a52b4)

**Comment by deepforest7** [comment]
I have back to version which support codellama/7b finetune.  but meet error Exception: Boolean value of Tensor with more than one value is ambiguous

**Comment by hazratisulton** [comment]
Thank you for reaching out about finetuning CodeLlama-7B. We've discontinued support for CodeLlama-7B, due to technical challenges. This includes previous versions where the model was present but not functioning optimally for all environments. This decision ensures our users have access to the most reliable and effective models.

We currently support a range of new models that offer significantly better quality and performance compared to CodeLlama-7B. Notably, models like "starcoder2" have been well-received by our community for their advanced capabilities and ease of finetuning.
